name: lightgcn_gowalla

# Dataset
dataset: gowalla

# Model
model: LightGCN_simple
embedding_type: IdEmbedding
embedding_dim: 512
num_layers: 1

# Training hyperparameters
loss: BPR
lr: 0.0001
epochs: 200
batch_size: 1024
lr_decay: 0.95
weight_decay: 0

# Graph preprocessing
add_edges: add_nothing
edge_weighting: ones

seed: 40013140