# Default config
name: "NCF"

# Dataset
dataset: simple

# Model type
model: "NCF"
embedding_type: "IdEmbeddingPlusNameEmbedding2"
embedding_dim: 256
num_layers: 3
dropout: 0.0

# Training parameters
loss: CE
nb_neg_sampling: 4
epochs: 800
lr: 0.0001
batch_size: 512
weight_decay: 0
lr_decay: 0.99
